package com.hyperactivity.android_app.core;

public enum Error {
	NO_ERROR,
	NOT_IMPLEMENTED,
	LOGIN_FAILED,
	PROFILE_NOT_FOUND, 
	PROFILE_UPLOAD_DENIED, 
	ID_MISMATCH, 
	NOT_LOADED, 
	CHANGE_PASSWORD_DENIED, 
	CATEGORY_NOT_FOUND, 
	CREATE_ACCOUNT_FAILED
}
